version: '3.8'

services:
  # 后端API服务
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    container_name: demo-backend
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=release
      - PORT=8080
    networks:
      - demo-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  # 前端Web服务
  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    container_name: demo-frontend
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - demo-network
    restart: unless-stopped

  # Rust工具程序
  tools:
    build:
      context: .
      dockerfile: docker/Dockerfile.tools
    container_name: demo-tools
    volumes:
      - ./data:/data
    networks:
      - demo-network
    profiles:
      - tools
    restart: "no"

networks:
  demo-network:
    driver: bridge
    name: demo-network

volumes:
  data:
    driver: local